# Generated by Django 5.2.1 on 2025-05-25 21:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodyPraktiki',
            fields=[
                ('nomer_perioda', models.AutoField(db_column='Nomer_perioda', primary_key=True, serialize=False)),
                ('god', models.IntegerField(db_column='God')),
                ('obem_v_chasah', models.SmallIntegerField(db_column='Obem_v_chasah')),
                ('data_nachala', models.DateField(db_column='Data_nachala')),
                ('data_vydachi_zadaniya', models.DateField(blank=True, db_column='Data_vydachi_zadaniya', null=True)),
                ('data_okonchaniya', models.DateField(db_column='Data_okonchaniya')),
            ],
            options={
                'db_table': 'Periody_praktiki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sezon',
            fields=[
                ('kod_sezona', models.AutoField(db_column='Kod_sezona', primary_key=True, serialize=False)),
                ('naimenovanie_sezona', models.CharField(db_column='Naimenovanie_sezona', unique=True)),
            ],
            options={
                'db_table': 'Sezon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('kod_tipa', models.CharField(db_column='Kod_tipa', primary_key=True, serialize=False)),
                ('naimenovanie_tipa', models.CharField(db_column='Naimenovanie_tipa', unique=True)),
            ],
            options={
                'db_table': 'Tip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
