# Generated by Django 5.2.1 on 2025-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialnosti',
            fields=[
                ('kod_specialnosti', models.CharField(db_column='Kod_specialnosti', primary_key=True, serialize=False)),
                ('nazvanie_specialnosti', models.CharField(db_column='Nazvanie_specialnosti', unique=True)),
            ],
            options={
                'db_table': 'Specialnosti',
                'managed': False,
            },
        ),
    ]
