# Generated by Django 5.2.1 on 2025-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_specialnosti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praktiki',
            fields=[
                ('nomer_praktiki', models.AutoField(db_column='Nomer_praktiki', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Praktiki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalnyeModuli',
            fields=[
                ('nomer_mdk', models.CharField(db_column='Nomer_MDK', primary_key=True, serialize=False)),
                ('naimenovanie_mdk', models.CharField(db_column='Naimenovanie_MDK')),
            ],
            options={
                'db_table': 'Professionalnye_moduli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RukovoditeliPraktik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Rukovoditeli_praktik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialnostiGruppy',
            fields=[
                ('nazvanie_gruppy', models.CharField(db_column='Nazvanie_gruppy', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Specialnosti_Gruppy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UchebnyjPlan',
            fields=[
                ('nomer_modulya', models.CharField(db_column='Nomer_modulya', primary_key=True, serialize=False)),
                ('naimenovanie_modulya', models.CharField(db_column='Naimenovanie_modulya', unique=True)),
                ('kompetencii', models.TextField(db_column='Kompetencii')),
            ],
            options={
                'db_table': 'Uchebnyj_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zadaniya',
            fields=[
                ('nomer_zadaniya', models.CharField(db_column='Nomer_zadaniya', primary_key=True, serialize=False)),
                ('nazvanie_temy', models.TextField(db_column='Nazvanie_temy')),
                ('vidy_rabot', models.TextField(db_column='Vidy_rabot')),
                ('kolichestvo_chasov_na_odnu_rabotu', models.SmallIntegerField(db_column='Kolichestvo_chasov_na_odnu_rabotu')),
            ],
            options={
                'db_table': 'Zadaniya',
                'managed': False,
            },
        ),
    ]
